# Aufbau Liste

Kombinieren der verschiedenen Informationen

## Importe

```{r}
library(tidyverse)
```

```{r message=F}
path = "../data/processed"
df_KWL <- read_csv(paste0(path, "/01_KWL_clean.csv"))
df_PLZ <- read_csv(paste0(path, "/02_foerdergebiete.csv"))
df_KW <- read_csv(paste0(path, "/05_KW_aggregate.csv"))
df_comb <- read_csv(paste0(path, "/04_combined.csv"))
```


## KVBG 

KWL filtern nach den Regionen
```{r}
df <- df_KWL %>% 
  left_join(df_PLZ, by = "plz", multiple="first") %>%
  mutate(KVBG_gebiet = if_else(
    is.na(Paragraph), F, T
  ), .before=Paragraph )
```

## MASTR

```{r}
df_mastr <- df_comb %>%
  select(nr_MASTR, nr_betreiber, nr_KW, breite, laenge)
```


```{r}
df <- df %>%
  left_join(df_mastr, by = "nr_MASTR")
```




## Saving



```{r}
write_csv(df, "../data/processed/03_KWL.csv")
```

Ein schneller Plot, wie viel KW-Kappa durch KVBG stillgelegt wird bis 2040

```{r}
df %>%
  # filter(stillegung_type=="KVBG") %>%
  select(leistung_brutto, jahr_stillegung) %>%
  group_by(jahr_stillegung) %>%
  summarise(total = sum(leistung_brutto)) %>%
  ungroup() %>%
  mutate(
    cum = cumsum(total),
    kappa = sum(total) - cum
    ) %>%
  ggplot(aes(x=jahr_stillegung, y=kappa)) +
  geom_line() 
```
